# -*- coding: utf-8 -*-
"""atm_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xg5V9pZxZeQ4gyvTkVF4Y0BiAK0CZ0nR
"""

def atm_simulator():
    balance = 1000  # Starting balance
    while True:
        # Display menu
        print("\nWelcome to the Virtual ATM!")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Exit")

        choice = input("Please select an option (1-4): ")

        # Process the user's choice
        if choice == '1':
            # Check balance
            print(f"\nYour current balance is: ${balance:.2f}")

        elif choice == '2':
            # Deposit money
            try:
                deposit_amount = float(input("Enter amount to deposit: $"))
                if deposit_amount > 0:
                    balance += deposit_amount
                    print(f"\nYou have successfully deposited ${deposit_amount:.2f}.")
                    print(f"New balance: ${balance:.2f}")
                else:
                    print("\nDeposit amount must be positive.")
            except ValueError:
                print("\nInvalid amount. Please enter a numeric value.")

        elif choice == '3':
            # Withdraw money
            try:
                withdraw_amount = float(input("Enter amount to withdraw: $"))
                if 0 < withdraw_amount <= balance:
                    balance -= withdraw_amount
                    print(f"\nYou have successfully withdrawn ${withdraw_amount:.2f}.")
                    print(f"Remaining balance: ${balance:.2f}")
                elif withdraw_amount > balance:
                    print("\nInsufficient balance for this withdrawal.")
                else:
                    print("\nWithdrawal amount must be positive.")
            except ValueError:
                print("\nInvalid amount. Please enter a numeric value.")

        elif choice == '4':
            # Exit the program
            print("\nThank you for using the Virtual ATM. Goodbye!")
            break

        else:
            print("\nInvalid option. Please select a number between 1 and 4.")

# Run the ATM simulator
atm_simulator()